# Generated by Django 3.1.3 on 2021-12-06 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.CharField(max_length=256, null=True)),
                ('filename', models.CharField(max_length=256)),
                ('fileUrl', models.CharField(blank=True, max_length=512, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fileList',
            },
        ),
        migrations.CreateModel(
            name='PPI_proteome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mask_id', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('combined_score', models.CharField(blank=True, max_length=128, null=True)),
                ('targets', models.CharField(blank=True, max_length=128, null=True)),
                ('Uniprot_accession_No', models.CharField(blank=True, max_length=128, null=True)),
                ('Sub_cellular', models.CharField(blank=True, max_length=128, null=True)),
                ('MSU_id', models.CharField(blank=True, max_length=128, null=True)),
                ('proj', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'ppi',
            },
        ),
        migrations.CreateModel(
            name='projectsamples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proj', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('concatsamples', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('distributions', models.CharField(blank=True, default='', max_length=100000, null=True)),
                ('compare', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'pcsddd4',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('mygit', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(default='red.jpg', upload_to='profile/image')),
                ('myInfo', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
