# Generated by Django 3.1.3 on 2021-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_uploadfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='files',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
