# Generated by Django 3.1.3 on 2021-12-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211207_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='filename',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
