# Generated by Django 3.1.3 on 2021-12-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_uploadfilemodel_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='username',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
