# Generated by Django 3.1.3 on 2021-12-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_uploadfilemodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='compare',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
