# Generated by Django 3.1.3 on 2021-12-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_uploadfilemodel_compare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='compare',
        ),
    ]
