# Generated by Django 3.1.3 on 2021-12-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_fileinfomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfomodel',
            name='whole',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
