# Generated by Django 3.1.3 on 2021-12-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_proteingroups2groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteingroups2groups',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
