# Generated by Django 2.2.14 on 2022-02-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20220113_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
