# Generated by Django 2.2.14 on 2022-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_uploadfilemodel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgfieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('upload_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('destxt', models.CharField(max_length=255)),
                ('projecttitle', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='photo',
        ),
    ]
