# Generated by Django 2.2.14 on 2022-02-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20220206_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgfieldmodel',
            old_name='destxt',
            new_name='attr',
        ),
        migrations.RemoveField(
            model_name='imgfieldmodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='imgfieldmodel',
            name='imagefiles',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
