# Generated by Django 2.2.14 on 2022-02-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20220207_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgfieldmodel',
            name='path2',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
