# Generated by Django 2.2.14 on 2022-02-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_imgfieldmodel_path2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='destxt',
            field=models.CharField(max_length=2550),
        ),
    ]
