# Generated by Django 2.2.14 on 2022-02-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20220210_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein_calcul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filteritem', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('proj_info', models.CharField(max_length=2550)),
                ('indexinfo', models.CharField(max_length=255)),
            ],
        ),
    ]
