# Generated by Django 2.2.14 on 2022-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_protein_calcul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein_calcultask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proteinids', models.CharField(blank=True, max_length=128, null=True)),
                ('majorityproteinids', models.CharField(blank=True, max_length=128, null=True)),
                ('fastaheaders', models.CharField(blank=True, max_length=128, null=True)),
                ('numberofproteins', models.CharField(blank=True, max_length=128, null=True)),
                ('peptides', models.CharField(blank=True, max_length=128, null=True)),
                ('uniquepeptides', models.CharField(blank=True, max_length=128, null=True)),
                ('sequencecoveragep', models.CharField(blank=True, max_length=128, null=True)),
                ('moldotweightkda', models.CharField(blank=True, max_length=128, null=True)),
                ('qhvalue', models.CharField(blank=True, max_length=128, null=True)),
                ('score', models.CharField(blank=True, max_length=128, null=True)),
                ('idsfrondevi', models.CharField(blank=True, max_length=128, null=True)),
                ('evidenceids', models.CharField(blank=True, max_length=128, null=True)),
                ('valuess', models.CharField(blank=True, max_length=5000, null=True)),
                ('proj', models.CharField(blank=True, max_length=128, null=True)),
                ('experiment', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('foldchange', models.CharField(blank=True, max_length=128, null=True)),
                ('pvalue', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='protein_calcul',
            name='id',
        ),
        migrations.AddField(
            model_name='protein_calcul',
            name='auto_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein_calcul',
            name='projidtitle',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
