# Generated by Django 2.2.14 on 2022-02-14 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20220214_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein_calcul',
            name='id',
        ),
        migrations.AddField(
            model_name='protein_calcul',
            name='auto_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
