# Generated by Django 2.2.14 on 2022-02-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20220214_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein_calcul',
            name='filteritem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protein_calcul',
            name='indexinfo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protein_calcul',
            name='proj_info',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='protein_calcul',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
