# Generated by Django 2.2.14 on 2022-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20220214_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein_calcultask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
