# Generated by Django 2.2.14 on 2022-02-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_protein_calcul_projidtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein_calcultask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
