# Generated by Django 2.2.14 on 2022-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_auto_20220215_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('proj_info', models.CharField(blank=True, max_length=2550, null=True)),
                ('projidtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
