# Generated by Django 2.2.14 on 2022-02-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_protein_calcul_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein_calcul',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
