# Generated by Django 2.2.14 on 2022-02-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_auto_20220218_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein_calcul',
            name='name',
        ),
    ]
