# Generated by Django 2.2.14 on 2022-03-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_remove_protein_calcul_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks_idinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('Analysisinfo', models.CharField(blank=True, max_length=255, null=True)),
                ('tos_MSUids', models.CharField(blank=True, max_length=10000, null=True)),
                ('Search_option', models.CharField(blank=True, max_length=255, null=True)),
                ('Search', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='searchNetworks_idinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('targets', models.CharField(blank=True, max_length=10000, null=True)),
                ('Search_option', models.CharField(blank=True, max_length=255, null=True)),
                ('Search', models.CharField(blank=True, max_length=255, null=True)),
                ('Analysisinfo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
