# Generated by Django 2.2.14 on 2022-03-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_networks_idinfo_searchnetwork_searchnetworks_idinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchnetwork',
            name='Search',
        ),
        migrations.RemoveField(
            model_name='searchnetwork',
            name='Search_option',
        ),
    ]
