# Generated by Django 2.2.14 on 2022-03-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_auto_20220302_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchnetwork',
            name='tos_MSUids',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
