# Generated by Django 2.2.14 on 2022-03-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_auto_20220303_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='GO_idinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Golist', models.CharField(blank=True, max_length=255, null=True)),
                ('items', models.CharField(blank=True, max_length=255, null=True)),
                ('go_cluster', models.CharField(blank=True, max_length=1000, null=True)),
                ('go_description', models.CharField(blank=True, max_length=255, null=True)),
                ('NOD', models.CharField(blank=True, max_length=255, null=True)),
                ('locINFO', models.CharField(blank=True, max_length=1000000, null=True)),
                ('Analysisinfo', models.CharField(blank=True, max_length=25500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='searchNetworks_idinfo',
        ),
    ]
