# Generated by Django 2.2.14 on 2022-03-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0039_auto_20220303_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_idinfo',
            name='fcpv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchnetwork',
            name='fcpv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
