# Generated by Django 2.2.14 on 2022-03-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0040_auto_20220303_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchnetwork',
            name='taskId',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
