# Generated by Django 2.2.14 on 2022-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0041_searchnetwork_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfomodel',
            name='FilterMethod',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileinfomodel',
            name='LabelMethod',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='FilterMethod',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='LabelMethod',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
