# Generated by Django 2.2.14 on 2022-03-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0043_uploadfilemodel_taskid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisinfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Analysisinfo', models.CharField(max_length=255)),
                ('proj', models.CharField(max_length=255)),
                ('compare', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('whole', models.CharField(max_length=255)),
                ('projecttitle', models.CharField(max_length=255)),
                ('LabelMethod', models.CharField(max_length=255, null=True)),
                ('FilterMethod', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
