# Generated by Django 2.2.14 on 2022-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0044_analysisinfomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinfomodel',
            name='AnalysisinfoTXT',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
