# Generated by Django 2.2.14 on 2022-04-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0046_protein_calcultask_chrinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinfomodel',
            name='taskId',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
