# Generated by Django 2.2.14 on 2022-04-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0047_analysisinfomodel_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinfomodel',
            name='indexinfo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
