# Generated by Django 2.2.14 on 2022-04-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0048_analysisinfomodel_indexinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='go_idinfo',
            old_name='NOD',
            new_name='counts',
        ),
        migrations.RenameField(
            model_name='go_idinfo',
            old_name='fcpv',
            new_name='fdr',
        ),
        migrations.RenameField(
            model_name='go_idinfo',
            old_name='locINFO',
            new_name='idconvert',
        ),
        migrations.AddField(
            model_name='analysisinfomodel',
            name='taskId2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
