# Generated by Django 2.2.14 on 2022-04-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0049_auto_20220412_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchnetwork',
            old_name='fcpv',
            new_name='case',
        ),
    ]
