# Generated by Django 2.2.14 on 2022-05-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0053_auto_20220510_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinfomodel',
            name='taskId3',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
