# Generated by Django 2.2.14 on 2022-05-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0054_analysisinfomodel_taskid3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networksinfo',
            name='taskId',
        ),
    ]
