# Generated by Django 2.2.14 on 2022-06-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0055_remove_networksinfo_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisinfomodel',
            name='compare',
            field=models.CharField(max_length=25500),
        ),
        migrations.AlterField(
            model_name='analysisinfomodel',
            name='whole',
            field=models.CharField(max_length=25500),
        ),
    ]
