# Generated by Django 2.2.14 on 2022-06-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0056_auto_20220608_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projgetinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=255)),
                ('userlist', models.CharField(max_length=2550)),
            ],
        ),
        migrations.AddField(
            model_name='projectinfomodel',
            name='userlist',
            field=models.CharField(default='dongu7610@naver.com', max_length=2550),
            preserve_default=False,
        ),
    ]
