# Generated by Django 2.2.14 on 2022-06-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0057_auto_20220609_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='projgetinfo',
            name='username',
            field=models.CharField(default='dongu7610@naver.com', max_length=255),
            preserve_default=False,
        ),
    ]
