# Generated by Django 2.2.14 on 2022-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0060_go_idinfo_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinfomodel',
            name='taskIdfin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='taskfin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
