# Generated by Django 2.2.14 on 2022-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0061_auto_20220624_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='userlist',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
