# Generated by Django 2.2.14 on 2022-06-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0062_uploadfilemodel_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksinfo',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchnetwork',
            name='project',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
