# Generated by Django 3.2 on 2022-07-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0063_auto_20220624_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfomodel',
            name='FilterMethod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfomodel',
            name='LabelMethod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfomodel',
            name='compare',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileinfomodel',
            name='destxt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileinfomodel',
            name='proj',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileinfomodel',
            name='projecttitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileinfomodel',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileinfomodel',
            name='whole',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
