# Generated by Django 3.2 on 2022-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0064_auto_20220728_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_idinfo',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='go_idinfo',
            name='pvfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
