# Generated by Django 3.2 on 2022-09-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0067_change2pmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='getFinNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ainfoid', models.CharField(blank=True, max_length=200)),
                ('mergeb123', models.CharField(blank=True, max_length=255)),
                ('c1source', models.CharField(blank=True, max_length=255)),
                ('c2target', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='analysisinfomodel',
            name='c1source',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='analysisinfomodel',
            name='c2target',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='analysisinfomodel',
            name='mergeb123',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='analysisinfomodel',
            name='taskId3fin',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
