# Generated by Django 3.2 on 2022-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0069_auto_20220906_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='projgetinfo',
            name='description',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
