# Generated by Django 3.2 on 2022-11-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0070_projgetinfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveErrorEXP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expname', models.CharField(blank=True, max_length=255, null=True)),
                ('taskid', models.CharField(blank=True, max_length=2550, null=True)),
            ],
        ),
    ]
