# Generated by Django 3.2 on 2022-11-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0071_removeerrorexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='removeerrorexp',
            name='projecttitle',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
