# Generated by Django 3.2 on 2022-11-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0073_auto_20221123_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentTodo',
        ),
        migrations.DeleteModel(
            name='DeleteModels',
        ),
        migrations.DeleteModel(
            name='Networks_idinfo',
        ),
        migrations.DeleteModel(
            name='proteinGroups2groups',
        ),
        migrations.DeleteModel(
            name='ReCommentTodo',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
