# Generated by Django 3.2.16 on 2023-02-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0075_auto_20230221_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysisidstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Analysisid', models.CharField(blank=True, max_length=255, null=True)),
                ('RelatedModels', models.CharField(blank=True, max_length=255, null=True)),
                ('finishmode', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskidandid',
            name='RelatedModels',
        ),
        migrations.RemoveField(
            model_name='taskidandid',
            name='finishmode',
        ),
    ]
