# Generated by Django 3.2.16 on 2023-02-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0076_auto_20230223_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network_nodeinfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodelist', models.CharField(blank=True, max_length=1000000, null=True)),
                ('edgelist', models.CharField(blank=True, max_length=1000000, null=True)),
                ('nodeinfo', models.CharField(blank=True, max_length=10000000, null=True)),
                ('notinmergest', models.CharField(blank=True, max_length=1000000, null=True)),
                ('Analysisid', models.CharField(blank=True, max_length=1000000, null=True)),
            ],
        ),
    ]
