# Generated by Django 3.2.16 on 2023-02-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0077_network_nodeinfomation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network_nodeinfomation',
            name='notinmergest',
        ),
    ]
