# Generated by Django 3.2 on 2024-01-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0079_auto_20230323_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragpipeProtein_calcultask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('majorityproteinids', models.CharField(blank=True, max_length=128, null=True)),
                ('proteinids', models.CharField(blank=True, max_length=128, null=True)),
                ('entryname', models.CharField(blank=True, max_length=128, null=True)),
                ('gene', models.CharField(blank=True, max_length=128, null=True)),
                ('proteinlength', models.CharField(blank=True, max_length=128, null=True)),
                ('coverage', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('valuess', models.CharField(blank=True, max_length=5000, null=True)),
                ('chrinfo', models.CharField(blank=True, max_length=5000, null=True)),
                ('proj', models.CharField(blank=True, max_length=128, null=True)),
                ('experiment', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('foldchange', models.CharField(blank=True, max_length=128, null=True)),
                ('pvalue', models.CharField(blank=True, max_length=128, null=True)),
                ('analyinfo', models.CharField(blank=True, max_length=128, null=True)),
                ('Analysisid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysisinfomodel',
            name='ImputeMethod',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='analysisinfomodel',
            name='NormMethod',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='analysisinfomodel',
            name='Software',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fileinfomodel',
            name='ImputeMethod',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fileinfomodel',
            name='NormMethod',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fileinfomodel',
            name='Software',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='protein_calcul',
            name='Software',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='ImputeMethod',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='NormMethod',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='Software',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='filename2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='files2',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
